Rutas y modificaciones (API->CRINMO)
BryanA26/Vue-Js pull request #23
Opened 2023-12-12 20:38 UTC by BryanA26

Closed #22 🍌 

Related at #24 ?

2023-12-12 21:17 UTC, JohnGolgota requested changes
Está incompleto, Falta la diferenciación real para la compilación de portada(web) y crinmo

2023-12-19 20:05 UTC, JohnGolgota commented
Necesito que lo veas e integres lo que se pueda salvar.

2023-12-20 13:05 UTC, karenjoha approved these changes

2023-12-21 14:25 UTC, closed without merging

2023-12-21 14:27 UTC, karenjoha commented
Estos cambios estan en la rama Formulario_mantenimiento #26 #27