Formulario Mantenimientos
BryanA26/Vue-Js pull request #27
Opened 2023-12-18 20:13 UTC by karenjoha

# Detalles de los cambios
El modulo pqrs se movio a una carpeta dentro de src/moduls/pqrs (correcion de urls)
Se integraron los cambios realizados el la rama routesCrinmo, no se se cambio nada relacionado al formulario PQRS, el formulario mantenimientos sigue sin realizar pruebas 

## Issues o Fixes
Progress #26
Close #29
## Antes de combinar las ramas
@JohnGolgota 

- [ ] Revisado por uno o más desarrolladores del equipo.
- [ ] tests.

2023-12-19 15:41 UTC, JohnGolgota approved these changes
Todo parece bien, las correcciones no son obligatorias para este punto.

2023-12-19 15:41 UTC, JohnGolgota commented on src/moduls/pqrs/pages/exportPDF.vue
> +		<img src="../../../../public/Image/Logo_Nitt.jpg" style="width: 200px;">
Los recursos públicos. no se acceden de esta forma.

2023-12-19 17:04 UTC, JohnGolgota requested changes
Questa pasando exactamente?

2023-12-19 17:04 UTC, JohnGolgota commented on package.json
> +    "path": false
Explica esto.

2023-12-19 17:04 UTC, JohnGolgota commented on src/moduls/mantenimientos/fetch.query.js
`fetch.query.js` es un recurso global si dentro tiene algo relacionado exclusivamente a mantenimientos... Se lleva solo esa parte

2023-12-21 14:22 UTC, JohnGolgota requested changes
No se responde. varias preguntas y comenta para comprobar si esto si es entregable.

2023-12-21 14:22 UTC, JohnGolgota commented on fetch.query.js
Esto pertenece al código fuente de la aplicación. quiero decir, porque salió de `src`?

2023-12-21 14:39 UTC, karenjoha commented on fetch.query.js
Trabajo en ese desarollo :(

2023-12-21 14:52 UTC, merged