Formulario matenimiento ya listo
BryanA26/Vue-Js pull request #32
Opened 2024-01-04 13:20 UTC by karenjoha

Integracion de enpoints y formulairio de mantenimiento listo

Closed #26

2024-01-04 14:14 UTC, JohnGolgota commented
@yeinernaranjo déjame un par de comentarios por ahí, que, que pereza.

2024-01-04 17:22 UTC, yeinernaranjo requested changes

2024-01-04 17:22 UTC, yeinernaranjo commented on src/moduls/mantenimientos/APIHandler.mantenimientos.js
> +const API_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImxvY2FsLXRlc3QtY2xpZW50LTAyIiwiaWF0IjoxNzAyOTk1NzI3LCJleHAiOjE3MzQ1MzE3Mjd9.mSTrPCZ3uEKaiPYWcNuT5TsFEyRVd0foJMMVMjz
Evita utilizar Tokens en el propio codigo de algun componente, usa variables de entorno dentro de un archivo `.env`

2024-01-04 17:22 UTC, yeinernaranjo commented on src/moduls/mantenimientos/pages/crear.vue
> +onMounted(async () => {
onMounted esta repetido, podrías colocar ambos await dentro del mismo

2024-01-04 17:22 UTC, yeinernaranjo commented on src/moduls/mantenimientos/pages/crear.vue
> +        const updateResponse = await fetch(`${UPDATE_URL}/${idMantenimiento}`, options);
Por que no utilizas las funciones que creaste en el `ApiHandler` para evitar crear una y otra vez las mismas funciones

2024-01-04 17:22 UTC, yeinernaranjo commented on src/moduls/mantenimientos/pages/crear.vue
> +        const options = {
Todas las `options` podrías guardarlas en una variable para evitar también estar escribiendo lo mismo, siempre se va a usar el mismo token.

2024-01-04 19:37 UTC, JohnGolgota requested changes
Hay un token expuesto y consultas fetch regadas por ahí por lo que ahora carece de sentido la existencia de la clase y las instancias...

2024-01-04 19:37 UTC, JohnGolgota commented on src/components/inputFile.vue
Porque el script esta así tan 🤮 tan 🤮 es muy 🤮

2024-01-04 19:37 UTC, JohnGolgota commented on src/moduls/mantenimientos/APIHandler.mantenimientos.js
> +const secondaryUrl = 'https://apicrinmo.azurewebsites.net/customer/create'
```suggestion
const azureWebAppApiEndpointCreateCustomer = 'https://apicrinmo.azurewebsites.net/customer/create'
```

2024-01-04 19:37 UTC, JohnGolgota commented on src/moduls/mantenimientos/APIHandler.mantenimientos.js
> +const url = 'https://apicrinmo.azurewebsites.net/maintenance/create';
```suggestion
const azureWebAppApiEndpointCreateMaintenance = 'https://apicrinmo.azurewebsites.net/maintenance/create';
```

2024-01-04 19:37 UTC, JohnGolgota commented on src/moduls/mantenimientos/APIHandler.mantenimientos.js
> +const API_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImxvY2FsLXRlc3QtY2xpZW50LTAyIiwiaWF0IjoxNzAyOTk1NzI3LCJleHAiOjE3MzQ1MzE3Mjd9.mSTrPCZ3uEKaiPYWcNuT5TsFEyRVd0foJMMVMjz
```suggestion
const azureWebAppApiEndpointCreateCustomer_API_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImxvY2FsLXRlc3QtY2xpZW50LTAyIiwiaWF0IjoxNzAyOTk1NzI3LCJleHAiOjE3MzQ1MzE3Mjd9.mSTrPCZ3uEKaiPYWcNuT5TsFEyRVd0foJMMVMjzczKA"
```
ESPERA WHAT?! que hace esto aquí? los tokens no se suben al repositorio!

2024-01-04 19:37 UTC, JohnGolgota commented on src/moduls/mantenimientos/pages/crear.vue
> +        const updateResponse = await fetch(`${UPDATE_URL}/${idMantenimiento}`, options);
Si existe una clase dedicada a actuar como controlador de las peticiones fetch, esto pa' que está aquí?

2024-01-04 19:51 UTC, JohnGolgota requested changes
pues eso, no me di cuenta en la anterior review.

2024-01-04 19:51 UTC, JohnGolgota commented on src/moduls/mantenimientos/pages/crear.vue
> +					<button type="submit" class="btn btn-primary" :disabled="enviando">ENVIAR</button>
Impide spammerar este botón.

2024-01-05 21:48 UTC, karenjoha commented
la cague

2024-01-10 16:55 UTC, JohnGolgota approved these changes

2024-01-10 16:55 UTC, merged