nuevo campo de indicativo telefonico
BryanA26/Vue-Js pull request #41
Opened 2024-01-16 17:59 UTC by karenjoha

Se creo un componente para ser reurilizado en los ortos formularios se implemento en mantenimientos
en progress porque aun falta implementarlo en los formularios creados y por crear

Progress #40

2024-01-17 20:32 UTC, JohnGolgota reviewed
![image](https://github.com/PORTADA-INMOBILIARIA-SAS/webapifront/assets/104475729/246fecbe-b9bf-4f4c-8fa1-2639d1cbd1ac)
Es esto o faltan instrucciones para probar el desarrollo?

2024-01-17 20:32 UTC, JohnGolgota commented on package.json
> +    "@trevoreyre/autocomplete-vue": "^2.4.1",
Las dependencias tienen que ser versiones fijas y como ya había dicho debe argumentarse en alguna parte, te lo simplifico:

- Necesidad puntual
- lista de alternativas que tuviste en cuenta con sus respectivas ventajas y desventajas.

Y podemos dejarlo ahí hasta que se me ocurran más formas de ser restrictivo.

2024-01-17 20:32 UTC, JohnGolgota commented on src/moduls/mantenimientos/pages/crear.vue
> +		const celphone = `${mantenimiento.value.celphoneExt} ${mantenimiento.value.celphone}`.replace(/\+/g, ''); // Elimina el símbolo '+'
```suggestion
		const celphone = `${mantenimiento.value.celphoneExt} ${mantenimiento.value.celphone}`;
```

Se eligió explícitamente el estándar para almacenar los números de teléfono:
`+prefijos_telefónicos_del_país número_telefónico`
`+` Porque sí básicamente, el prefijo y el número de teléfono deben estar separados por un espacio. format: UTF-8 CRLF

2024-01-18 20:05 UTC, karenjoha commented on package.json
> +    "@trevoreyre/autocomplete-vue": "^2.4.1",
la necesidad de esta dependecia fue poder poner la bandera en el datalist del indicativo telefonico ya que un no se pueden editar las opciones directamente de un datalis

ventajas
- facil uso
- no tiene ninguna dependecia
-

2024-01-22 13:27 UTC, JohnGolgota requested changes
![image](https://github.com/PORTADA-INMOBILIARIA-SAS/webapifront/assets/104475729/3cc55b0b-d89e-4628-992e-2cd97b69b7c1)

Quita ese desplegable, nos interesa que solo aparezcan las opciones que hay en ese select, y pregunta: la creación del usuario sigue dependiendo del correo y la cedula o solo de la cedula como habían sugerido en otra parte?

2024-01-31 15:12 UTC, JohnGolgota approved these changes
Documenta más el motivo por el que recurres a usar una dependencia nueva, como debe ser teniendo en cuenta las características y ventajas que presenta ante las alternativas incluida el hacerlo a mano, como lo presento recientemente @BryanA26 en el componente de búsqueda aplicado en la página.

resuelve conflictos, recuerda poner aprueba el resultado

2024-02-29 17:29 UTC, JohnGolgota reviewed
@karenjoha no había superado ya esta fase? que hace afectando dos módulos en un PR?

2024-02-29 17:29 UTC, JohnGolgota commented on package-lock.json
??

2024-04-18 16:57 UTC, merged